FROM python:3.10

WORKDIR /estimasi_mobil

ADD requirements.txt /estimasi_mobil/

ADD . /estimasi_mobil/ 
RUN pip install -r requirements.txt
ENV UNCERTAINTY_THRESHOLD=0.6

CMD ["python", "estimasi_mobil.py"]